# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chandra Nadiminti
email: nadiminti.chandra@gmail.com
url: https://cnadiminti.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Job role
role: Software Designer
# Social networks usernames
social:
  - title: github
    url: http://github.com/cnadiminti
  - title: facebook
    url: https://www.facebook.com/chandramohanbabu.nadiminti
  - title: linkedin
    url: https://www.linkedin.com/in/chandranadiminti


# Postal address (add as many lines as necessary)
address:
  - line: 3507 Palmilla Drive
  - line: San Jose, CA 95134

# Build settings
markdown: kramdown
permalink: pretty
